# Generated by Django 3.2.15 on 2023-01-13 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "priority",
                    models.IntegerField(
                        choices=[
                            (1, "Trivial"),
                            (2, "Minor"),
                            (3, "Major"),
                            (4, "Critical"),
                            (5, "Blocker"),
                        ]
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (1, "Bug"),
                            (2, "Enhancement"),
                            (3, "Request"),
                            (4, "Task"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Open"),
                            (2, "Development"),
                            (3, "QA"),
                            (4, "Closed"),
                        ]
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
