# Generated by Django 3.2.15 on 2023-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Trivial'), (2, 'Minor'), (3, 'Major'), (4, 'Critical'), (5, 'Blocker')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='type',
            field=models.IntegerField(choices=[(1, 'Bug'), (2, 'Enhancement'), (3, 'Request'), (4, 'Task')], default=1),
            preserve_default=False,
        ),
    ]
