# Generated by Django 3.2.15 on 2023-01-05 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_auto_20230105_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.IntegerField(choices=[(1, 'Open'), (2, 'Development'), (3, 'QA'), (4, 'Closed')], default=1),
            preserve_default=False,
        ),
    ]
