# Generated by Django 3.2.15 on 2023-01-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230107_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatar_images'),
        ),
        migrations.AddField(
            model_name='user',
            name='cover_img',
            field=models.ImageField(blank=True, upload_to='cover_images'),
        ),
    ]
